In [49]:
import warnings
warnings.filterwarnings('ignore')

In [50]:
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
#plt.rcParams['figure.figsize'] = (15.0,7.0)

In [51]:
from sklearn.datasets import load_iris

In [52]:
iris = load_iris()

In [53]:
iris_df = pd.DataFrame(iris.data,columns=iris.feature_names)

In [54]:
print(iris_df.shape)

(150, 4)


In [55]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [56]:
iris_df['target'] = iris.target

In [57]:
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [58]:
X = iris_df.drop(labels=['target'],axis=1).values
y = iris_df.target.values

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [61]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [62]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [63]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
svc = SVC()

In [64]:
svc.fit(X_train_scaled,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

## TrainData

In [65]:
y_train_pred_svc = svc.predict(X_train_scaled)

In [66]:
print('Accuracy_Score: ',accuracy_score(y_train,y_train_pred_svc))
print()
print(confusion_matrix(y_train,y_train_pred_svc))
print()
print(classification_report(y_train,y_train_pred_svc))

Accuracy_Score:  0.9809523809523809

[[37  0  0]
 [ 0 29  1]
 [ 0  1 37]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.97      0.97      0.97        30
           2       0.97      0.97      0.97        38

    accuracy                           0.98       105
   macro avg       0.98      0.98      0.98       105
weighted avg       0.98      0.98      0.98       105



## TestData

In [67]:
y_test_pred_svc = svc.predict(X_test_scaled)

In [68]:
print('Accuracy_Score: ',accuracy_score(y_test,y_test_pred_svc))
print()
print(confusion_matrix(y_test,y_test_pred_svc))
print()
print(classification_report(y_test,y_test_pred_svc))

Accuracy_Score:  0.9777777777777777

[[13  0  0]
 [ 0 19  1]
 [ 0  0 12]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.95      0.97        20
           2       0.92      1.00      0.96        12

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



In [78]:
svc = SVC()

In [79]:
svc.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [80]:
parameters = {'C':[.001,.01,.1,1,10,100,1000,10000],
             'kernel':['linear','rbf'],
             'degree':[1,2,3,4],
             'gamma':[.001,.01,.1,1,10,100,1000,10000]}

In [81]:
from sklearn.model_selection import GridSearchCV
gcv = GridSearchCV(svc,parameters,cv=5,return_train_score=True,refit=True)

In [82]:
gcv.fit(X_train,y_train)

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000],
                         'degree': [1, 2, 3, 4],
                         'gamma': [0.001, 0.01, 0.1, 1, 10, 100, 1000, 10000],
                         'kernel': ['linear', 'rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
             scoring=None, verbose=0)

In [83]:
gcv.best_estimator_

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=1, gamma=0.001, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [84]:
gcv.best_score_

0.9619047619047619

In [85]:
gcv.best_index_

192

In [88]:
gcv.best_params_

{'C': 1, 'degree': 1, 'gamma': 0.001, 'kernel': 'linear'}

In [121]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [122]:
svc = SVC(C=1, degree=1, gamma=0.001, kernel='linear')

In [123]:
svc.fit(X_train,y_train)

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=1, gamma=0.001, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [124]:
y_pred_svcTrain = svc.predict(X_train)

In [125]:
print('Accuracy_Score: ',accuracy_score(y_train,y_pred_svcTrain))
print()
print(confusion_matrix(y_train,y_pred_svcTrain))
print()
print(classification_report(y_train,y_pred_svcTrain))

Accuracy_Score:  0.9904761904761905

[[37  0  0]
 [ 0 29  1]
 [ 0  0 38]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       1.00      0.97      0.98        30
           2       0.97      1.00      0.99        38

    accuracy                           0.99       105
   macro avg       0.99      0.99      0.99       105
weighted avg       0.99      0.99      0.99       105



In [126]:
y_pred_svcTest = svc.predict(X_test)

In [127]:
print('Accuracy_Score: ',accuracy_score(y_test,y_pred_svcTest))
print()
print(confusion_matrix(y_test,y_pred_svcTest))
print()
print(classification_report(y_test,y_pred_svcTest))

Accuracy_Score:  1.0

[[13  0  0]
 [ 0 20  0]
 [ 0  0 12]]

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        20
           2       1.00      1.00      1.00        12

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

