In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
import seaborn as sns

In [15]:
a = np.arange(132).reshape(11,12)
a

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131]])

In [14]:
a[8,3]

99

In [58]:
b = np.array ([[4, 3, 1], [5, 7, 0], [9, 9, 3], [8, 2, 4]])
b

array([[4, 3, 1],
       [5, 7, 0],
       [9, 9, 3],
       [8, 2, 4]])

In [50]:
b[2:3]

array([[9, 9, 3]])

In [51]:
b[0:1]

array([[4, 3, 1]])

In [59]:
b[[0,2]] = b[[2,0]]

In [60]:
b

array([[9, 9, 3],
       [5, 7, 0],
       [4, 3, 1],
       [8, 2, 4]])

In [61]:
b[[0,2]]

array([[9, 9, 3],
       [4, 3, 1]])

In [62]:
b[[2,0]]

array([[4, 3, 1],
       [9, 9, 3]])