In [3]:
import numpy as np
a = np.array([1+2j, 3+4j, 5+6j,2j,2])

In [4]:
np.isreal(a)

array([False, False, False, False,  True])

In [5]:
np.iscomplex(a)

array([ True,  True,  True,  True, False])

In [6]:
b = np.array([1,2,3])
c = np.array([5,6,7])
print(np.dot(b,c))
print(np.dot(c,b))

38
38


In [7]:
d = np.array([[2,3],[5,6]])
e = np.array([[4,5,6],[6,7,8]])
print(np.shape(d))
print(np.shape(e))
print(np.dot(d,e))

(2, 2)
(2, 3)
[[26 31 36]
 [56 67 78]]


In [8]:
d

array([[2, 3],
       [5, 6]])

In [9]:
e

array([[4, 5, 6],
       [6, 7, 8]])

In [10]:
np.greater(b,c)

array([False, False, False])

In [11]:
np.greater_equal(c,b)

array([ True,  True,  True])

In [12]:
np.add(b,c)

array([ 6,  8, 10])

In [13]:
f = 100*(np.random.rand(36).reshape(6,6))
print(np.round(f))
f.dtype

[[38. 95. 67. 27. 56. 86.]
 [92. 50. 49.  9. 50. 20.]
 [89. 35. 65. 82. 25. 58.]
 [10. 93. 82. 52. 49.  5.]
 [55.  7. 11. 65. 43. 16.]
 [86. 22. 38. 47. 57. 14.]]


dtype('float64')

In [14]:
np.sqrt(f)

array([[6.16109265, 9.72953256, 8.16002681, 5.21075258, 7.51509006,
        9.28110812],
       [9.56746864, 7.08842535, 7.03253672, 3.07316039, 7.06119032,
        4.43277023],
       [9.42295678, 5.91379149, 8.03315992, 9.07941747, 5.04590255,
        7.59995899],
       [3.08803586, 9.63895109, 9.07115048, 7.23398876, 7.01213608,
        2.19215236],
       [7.44220872, 2.66089983, 3.34108933, 8.08139599, 6.56006753,
        3.95986088],
       [9.27684417, 4.69621618, 6.1498651 , 6.87212999, 7.56471735,
        3.73252287]])

In [15]:
np.exp(f)

array([[3.05781657e+16, 1.29409941e+41, 8.27844350e+28, 6.19353737e+11,
        3.36873170e+24, 2.56849347e+37],
       [5.67254330e+39, 6.62921904e+21, 3.01104057e+21, 1.26361218e+04,
        4.50920888e+21, 3.41702798e+08],
       [3.64691229e+38, 1.54365572e+15, 1.06106778e+28, 6.33027271e+35,
        1.14190343e+11, 1.21500640e+25],
       [1.38489610e+04, 2.23887718e+40, 5.44824097e+35, 5.33197294e+22,
        2.26090549e+21, 1.22184471e+02],
       [1.13250088e+24, 1.18842943e+03, 7.04654602e+04, 2.30845503e+28,
        4.89372761e+18, 6.45585626e+06],
       [2.37308169e+37, 3.78550990e+09, 2.66306915e+16, 3.23642323e+20,
        7.11999066e+24, 1.12323897e+06]])

In [16]:
np.sin(f)

array([[ 0.25703297,  0.404127  , -0.57498993,  0.90113979, -0.07202678,
        -0.96770616],
       [-0.41711552, -0.01970722, -0.72353504, -0.0195356 , -0.39408657,
         0.71728362],
       [ 0.73625548, -0.40356569,  0.99168988,  0.68486075,  0.32252075,
         0.93586602],
       [-0.11095858, -0.97311762,  0.56823725,  0.8802941 , -0.88912518,
        -0.99566533],
       [-0.91767831,  0.71540432, -0.98603736,  0.6166535 , -0.81214035,
         0.02746159],
       [-0.94475168, -0.0632556 ,  0.12142851, -0.10210259,  0.6258968 ,
         0.97897133]])

In [17]:
np.matmul(d,e)

array([[26, 31, 36],
       [56, 67, 78]])

In [18]:
np.max(d)

6

In [19]:
np.log(a)

array([0.80471896+1.10714872j, 1.60943791+0.92729522j,
       2.05543693+0.87605805j, 0.69314718+1.57079633j,
       0.69314718+0.j        ])

In [20]:
np.linalg.inv(d)

array([[-2.        ,  1.        ],
       [ 1.66666667, -0.66666667]])

In [21]:
np.linalg.det(d)

-2.999999999999999

In [22]:
g = np.arange(36).reshape(6,6)
g

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [23]:
g[:,:3]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20],
       [24, 25, 26],
       [30, 31, 32]])

In [172]:
g[2,0:]

array([12, 13, 14, 15, 16, 17])

In [173]:
g[:,]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [174]:
g[1,1]

7

In [175]:
g[2:4,2:5]

array([[14, 15, 16],
       [20, 21, 22]])

In [176]:
g[2:,5:]

array([[17],
       [23],
       [29],
       [35]])

In [177]:
g[[0,4],2:]

array([[ 2,  3,  4,  5],
       [26, 27, 28, 29]])

In [178]:
g[2:,[0,1,5]]

array([[12, 13, 17],
       [18, 19, 23],
       [24, 25, 29],
       [30, 31, 35]])