In [18]:
import numpy as np
a=np.array([[3,4,5,6,7]])
print(a)
print(a.ndim)
a.shape
a.dtype

[[3 4 5 6 7]]
2


dtype('int32')

In [21]:
b=np.array([[[1,2,3],[2,3,4],[5,6,7],[8,9,10]]])
print(b.ndim)
print(b.dtype)
b

3
int32


array([[[ 1,  2,  3],
        [ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]]])

In [16]:
b.shape

(1, 4, 3)

In [22]:
c=np.array(['rak','a','b'])
c.dtype

dtype('<U3')

In [24]:
d=np.array([1.1,2.3,4.5])
d.dtype

dtype('float64')

In [28]:
e=np.array([1.1,2.4,45,6.7],dtype=int)
print(e.dtype)
e

int32


array([ 1,  2, 45,  6])

In [30]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
o=np.ones(5)
o

array([1., 1., 1., 1., 1.])

In [35]:
z=np.zeros(((10,5,2)))
z

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [36]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
p=np.arange(10)
p=p.reshape(5,2)
p

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [48]:
q=np.arange(10,101,5)
print(q.shape)
q

(19,)


array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [53]:
r=np.arange(100,200,5).reshape(4,5)
r

array([[100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170],
       [175, 180, 185, 190, 195]])

In [55]:
r+2

array([[102, 107, 112, 117, 122],
       [127, 132, 137, 142, 147],
       [152, 157, 162, 167, 172],
       [177, 182, 187, 192, 197]])

In [57]:
r-2

array([[ 98, 103, 108, 113, 118],
       [123, 128, 133, 138, 143],
       [148, 153, 158, 163, 168],
       [173, 178, 183, 188, 193]])

In [58]:
r/2

array([[50. , 52.5, 55. , 57.5, 60. ],
       [62.5, 65. , 67.5, 70. , 72.5],
       [75. , 77.5, 80. , 82.5, 85. ],
       [87.5, 90. , 92.5, 95. , 97.5]])

In [59]:
r%2

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [60]:
r**2

array([[10000, 11025, 12100, 13225, 14400],
       [15625, 16900, 18225, 19600, 21025],
       [22500, 24025, 25600, 27225, 28900],
       [30625, 32400, 34225, 36100, 38025]], dtype=int32)

In [62]:
r*2

array([[200, 210, 220, 230, 240],
       [250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390]])

In [64]:
x=np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
y=np.hsplit(x,2)
y

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [67]:
v=np.vsplit(x,2)
v

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [72]:
a=np.arange(16).reshape(4,4)
b=np.arange(16).reshape(4,4)
z=np.hstack((a,b))
z

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [12, 13, 14, 15, 12, 13, 14, 15]])

In [74]:
c=np.vstack((a,b))
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
a=np.random.randint(10,100,10).reshape(5,2)
a

array([[44, 50],
       [96, 31],
       [85, 94],
       [15, 98],
       [82, 16]])

In [98]:
b=np.random.randn(10,10)
b

array([[-0.59413377, -0.68153708,  1.94649934,  0.34967369,  1.31278739,
        -0.08231673, -0.13846453,  1.70734835,  0.56793763, -0.03875994],
       [-0.28117066,  0.46808523, -0.04619455,  0.54898805,  0.7098415 ,
         0.24310994, -0.5553695 ,  0.55800886, -1.03002666, -0.08329   ],
       [-0.09788094, -0.00268132,  0.56357974, -2.67050902, -1.19997497,
         0.18436759,  0.90633211, -0.88149992, -0.64241018,  0.97382879],
       [-1.92224943, -0.7466061 ,  1.22112509,  0.2153388 ,  0.06287084,
        -0.37832452,  2.42931382,  0.10232398, -0.86742931,  0.11405006],
       [-1.16564541, -1.01970506,  0.6072473 , -0.70083051,  0.0788772 ,
         0.49085517, -0.76286635, -0.3656601 , -0.86938115, -1.14944057],
       [ 0.15379415, -0.84526042, -0.48171887,  1.41803713,  0.41885688,
        -1.17320625,  1.28107956, -0.86367866,  0.72814667, -0.17757038],
       [-2.30486693,  0.74592125, -0.9107031 , -0.09091483, -1.15166119,
        -0.13042951,  0.50226177, -0.00919568

In [101]:
a=[1,2,3,4]
b=a
b[1]=3
a

[1, 3, 3, 4]

In [106]:
b=a.copy()
b[1]=4
print(a)
print(b)

[1, 3, 3, 4]
[1, 4, 3, 4]


In [111]:
np.linspace(1,30,10).reshape(5,2)

array([[ 1.        ,  4.22222222],
       [ 7.44444444, 10.66666667],
       [13.88888889, 17.11111111],
       [20.33333333, 23.55555556],
       [26.77777778, 30.        ]])

In [114]:
a=np.array([10,11,12,15,9,4])

In [118]:
print(a.min())
print(a.max())
print(a.argmin())
print(a.argmax())

4
15
5
3


In [125]:
a=np.array([10,11,12,15,9,4])
b=np.array([1,2,3,4,5,0])
print(np.all(a))
print(np.all(b))
print(np.any(a))
print(np.any(b))

True
False
True
True


In [130]:
b=np.array([1+2j,3+4j,5j])
print(np.isreal(b))
print(np.iscomplex(b))
b

[False False False]
[ True  True  True]


array([1.+2.j, 3.+4.j, 0.+5.j])

In [139]:
a=np.array([[10,11,12],[13,14,15]])
b=np.array([[1,2,3],[4,5,6],[2,3,5]])
print(np.dot(a,b))

[[ 78 111 156]
 [ 99 141 198]]


In [143]:
a=np.array([10,11,12,15,9,4])
b=np.array([1,2,3,4,5,0])
print(np.greater(a,b))
print(np.greater_equal(a,b))

[ True  True  True  True  True  True]
[ True  True  True  True  True  True]


In [150]:
a=np.round(100*(np.random.rand(36).reshape(6,6)))
print(a.dtype)
a



float64


array([[56., 20., 31., 97., 98., 30.],
       [ 1., 44., 96., 56., 87., 64.],
       [76., 40., 63.,  3., 17., 65.],
       [18., 24., 16., 16.,  6., 84.],
       [24., 90., 93., 78., 83., 27.],
       [98., 19., 87., 16., 12.,  7.]])

In [152]:
np.round(np.sqrt(a))

array([[ 7.,  4.,  6., 10., 10.,  5.],
       [ 1.,  7., 10.,  7.,  9.,  8.],
       [ 9.,  6.,  8.,  2.,  4.,  8.],
       [ 4.,  5.,  4.,  4.,  2.,  9.],
       [ 5.,  9., 10.,  9.,  9.,  5.],
       [10.,  4.,  9.,  4.,  3.,  3.]])

In [153]:
np.exp(a)

array([[2.09165950e+24, 4.85165195e+08, 2.90488497e+13, 1.33833472e+42,
        3.63797095e+42, 1.06864746e+13],
       [2.71828183e+00, 1.28516001e+19, 4.92345829e+41, 2.09165950e+24,
        6.07603023e+37, 6.23514908e+27],
       [1.01480039e+33, 2.35385267e+17, 2.29378316e+27, 2.00855369e+01,
        2.41549528e+07, 1.69488924e+28],
       [6.56599691e+07, 2.64891221e+10, 8.88611052e+06, 8.88611052e+06,
        4.03428793e+02, 3.02507732e+36],
       [2.64891221e+10, 1.22040329e+39, 2.45124554e+40, 7.49841700e+33,
        1.11286375e+36, 5.32048241e+11],
       [3.63797095e+42, 1.78482301e+08, 6.07603023e+37, 8.88611052e+06,
        1.62754791e+05, 1.09663316e+03]])

In [154]:
np.sin(a)

array([[-0.521551  ,  0.91294525, -0.40403765,  0.37960774, -0.57338187,
        -0.98803162],
       [ 0.84147098,  0.01770193,  0.98358775, -0.521551  , -0.82181784,
         0.92002604],
       [ 0.56610764,  0.74511316,  0.1673557 ,  0.14112001, -0.96139749,
         0.82682868],
       [-0.75098725, -0.90557836, -0.28790332, -0.28790332, -0.2794155 ,
         0.73319032],
       [-0.90557836,  0.89399666, -0.94828214,  0.51397846,  0.96836446,
         0.95637593],
       [-0.57338187,  0.14987721, -0.82181784, -0.28790332, -0.53657292,
         0.6569866 ]])

In [155]:
a=np.array([[10,11,12],[13,14,15]])
b=np.array([[1,2,3],[4,5,6],[2,3,5]])
np.matmul(a,b)

array([[ 78, 111, 156],
       [ 99, 141, 198]])

In [157]:
#linear algebra
b=np.array([[1,2,3],[4,5,6],[2,3,5]])
np.linalg.inv(b)

array([[-2.33333333,  0.33333333,  1.        ],
       [ 2.66666667,  0.33333333, -2.        ],
       [-0.66666667, -0.33333333,  1.        ]])

In [158]:
np.linalg.det(b)

-2.9999999999999996

In [187]:
b=np.array([[1,2,3,4,5,6],[4,5,6,7,8,9],[2,3,5,6,7,8],[7,8,9,1,2,3],[2,5,7,9,1,5]])
b

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9],
       [2, 3, 5, 6, 7, 8],
       [7, 8, 9, 1, 2, 3],
       [2, 5, 7, 9, 1, 5]])

In [168]:
b[1,1]

5

In [185]:
b[1:3,2:4]

array([[6, 7],
       [5, 6]])

In [197]:
b[1:3,2:5]

array([[6, 7, 8],
       [5, 6, 7]])

In [217]:
b[1:5,[0,1,5]]

array([[4, 5, 9],
       [2, 3, 8],
       [7, 8, 3],
       [2, 5, 5]])

In [219]:
b[[0,3],2:]

array([[3, 4, 5, 6],
       [9, 1, 2, 3]])