In [61]:
import warnings
warnings.filterwarnings('ignore')

In [62]:
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
#plt.rcParams['figure.figsize'] = (15.0,7.0)

In [63]:
social_nw = pd.read_csv('Social_Network_Ads.csv')
print(social_nw.shape)
social_nw.head()

(400, 5)


User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [64]:
social_nw.isnull().sum().sum()

0

In [65]:
social = pd.get_dummies(social_nw,drop_first=True)
social.head()

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0  15624510   19            19000          0            1
1  15810944   35            20000          0            1
2  15668575   26            43000          0            0
3  15603246   27            57000          0            0
4  15804002   19            76000          0            1

In [66]:
social.drop('User ID',axis=1,inplace=True)

In [67]:
X = social.drop('Purchased',axis=1).values
y = social.Purchased.values

In [69]:
from sklearn.model_selection import train_test_split

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [71]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [72]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [73]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
ga = GaussianNB()

In [74]:
ga.fit(X_train_scaled,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

## Train Data

In [75]:
y_pred_train_ga = ga.predict(X_train_scaled)

In [76]:
print('Accuracy_Score: ',accuracy_score(y_train,y_pred_train_ga))
print()
print(confusion_matrix(y_train,y_pred_train_ga))
print()
print(classification_report(y_train,y_pred_train_ga))

Accuracy_Score:  0.8642857142857143

[[172  12]
 [ 26  70]]

              precision    recall  f1-score   support

           0       0.87      0.93      0.90       184
           1       0.85      0.73      0.79        96

    accuracy                           0.86       280
   macro avg       0.86      0.83      0.84       280
weighted avg       0.86      0.86      0.86       280



## Test Data

In [77]:
y_pred_test_ga = ga.predict(X_test_scaled)

In [78]:
print('Accuracy_Score: ',accuracy_score(y_test,y_pred_test_ga))
print()
print(confusion_matrix(y_test,y_pred_test_ga))
print()
print(classification_report(y_test,y_pred_test_ga))

Accuracy_Score:  0.9083333333333333

[[71  2]
 [ 9 38]]

              precision    recall  f1-score   support

           0       0.89      0.97      0.93        73
           1       0.95      0.81      0.87        47

    accuracy                           0.91       120
   macro avg       0.92      0.89      0.90       120
weighted avg       0.91      0.91      0.91       120



In [79]:
from sklearn.naive_bayes import BernoulliNB
ba = BernoulliNB()

In [80]:
ba.fit(X_train_scaled,y_train)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

## Train Data

In [83]:
y_pred_train_ba = ba.predict(X_train_scaled)

In [84]:
print('Accuracy_Score: ',accuracy_score(y_train,y_pred_train_ba))
print()
print(confusion_matrix(y_train,y_pred_train_ba))
print()
print(classification_report(y_train,y_pred_train_ba))

Accuracy_Score:  0.725

[[158  26]
 [ 51  45]]

              precision    recall  f1-score   support

           0       0.76      0.86      0.80       184
           1       0.63      0.47      0.54        96

    accuracy                           0.73       280
   macro avg       0.69      0.66      0.67       280
weighted avg       0.71      0.72      0.71       280



## Test Data

In [85]:
y_pred_test_ba = ba.predict(X_test_scaled)

In [86]:
print('Accuracy_Score: ',accuracy_score(y_test,y_pred_test_ba))
print()
print(confusion_matrix(y_test,y_pred_test_ba))
print()
print(classification_report(y_test,y_pred_test_ba))

Accuracy_Score:  0.725

[[66  7]
 [26 21]]

              precision    recall  f1-score   support

           0       0.72      0.90      0.80        73
           1       0.75      0.45      0.56        47

    accuracy                           0.73       120
   macro avg       0.73      0.68      0.68       120
weighted avg       0.73      0.72      0.71       120



In [87]:
from sklearn.naive_bayes import MultinomialNB
ml = MultinomialNB()

In [91]:
from sklearn.preprocessing import MinMaxScaler
minmax = MinMaxScaler()

In [92]:
X_train_minmax = minmax.fit_transform(X_train)
X_test_minmax = minmax.transform(X_test)

In [93]:
ml.fit(X_train_minmax,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

## Train Data

In [94]:
y_pred_train_ml = ml.predict(X_train_minmax)

In [95]:
print('Accuracy_Score: ',accuracy_score(y_train,y_pred_train_ml))
print()
print(confusion_matrix(y_train,y_pred_train_ml))
print()
print(classification_report(y_train,y_pred_train_ml))

Accuracy_Score:  0.6571428571428571

[[184   0]
 [ 96   0]]

              precision    recall  f1-score   support

           0       0.66      1.00      0.79       184
           1       0.00      0.00      0.00        96

    accuracy                           0.66       280
   macro avg       0.33      0.50      0.40       280
weighted avg       0.43      0.66      0.52       280



## Test Data

In [96]:
y_pred_test_ml = ml.predict(X_test_minmax)

In [97]:
print('Accuracy_Score: ',accuracy_score(y_test,y_pred_test_ml))
print()
print(confusion_matrix(y_test,y_pred_test_ml))
print()
print(classification_report(y_test,y_pred_test_ml))

Accuracy_Score:  0.6083333333333333

[[73  0]
 [47  0]]

              precision    recall  f1-score   support

           0       0.61      1.00      0.76        73
           1       0.00      0.00      0.00        47

    accuracy                           0.61       120
   macro avg       0.30      0.50      0.38       120
weighted avg       0.37      0.61      0.46       120

